// <auto-generated />
using System;
using KellyTestProject.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KellyTestProject.Migrations
{
    [DbContext(typeof(MsSqlContext))]
    [Migration("20201130193912_CreateProcedure")]
    partial class CreateProcedure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KellyTestProject.Model.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Раздел 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Раздел 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Раздел 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Раздел 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Раздел 5"
                        });
                });

            modelBuilder.Entity("KellyTestProject.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Иван",
                            Patronymic = "Иванович",
                            Surname = "Иванов"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Пётр",
                            Patronymic = "Петрович",
                            Surname = "Петров"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Семён",
                            Patronymic = "Семёныч",
                            Surname = "Смирнов"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Александр",
                            Patronymic = "Александрович",
                            Surname = "Александров"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Максим",
                            Patronymic = "Максимы",
                            Surname = "Максимов"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Имя1",
                            Patronymic = "Отчество1",
                            Surname = "Фамилия1"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Имя2",
                            Patronymic = "Отчество2",
                            Surname = "Фамилия2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Имя3",
                            Patronymic = "Отчество3",
                            Surname = "Фамилия3"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Имя4",
                            Patronymic = "Отчество4",
                            Surname = "Фамилия4"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Имя5",
                            Patronymic = "Отчество5",
                            Surname = "Фамилия5"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Имя6",
                            Patronymic = "Отчество6",
                            Surname = "Фамилия6"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Имя7",
                            Patronymic = "Отчество7",
                            Surname = "Фамилия7"
                        });
                });

            modelBuilder.Entity("KellyTestProject.Model.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTimeVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTimeVisit = new DateTime(2018, 6, 17, 23, 29, 14, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTimeVisit = new DateTime(2021, 7, 26, 23, 22, 34, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateTimeVisit = new DateTime(2018, 8, 18, 2, 11, 43, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateTimeVisit = new DateTime(2019, 6, 19, 0, 3, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateTimeVisit = new DateTime(2020, 6, 3, 11, 3, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            DateTimeVisit = new DateTime(2017, 1, 25, 21, 25, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateTimeVisit = new DateTime(2017, 6, 14, 4, 0, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            DateTimeVisit = new DateTime(2021, 10, 14, 17, 55, 59, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            DateTimeVisit = new DateTime(2019, 6, 29, 14, 23, 41, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            DateTimeVisit = new DateTime(2021, 5, 6, 5, 4, 45, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            DateTimeVisit = new DateTime(2021, 4, 7, 14, 29, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            DateTimeVisit = new DateTime(2019, 10, 4, 6, 2, 32, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 13,
                            DateTimeVisit = new DateTime(2017, 8, 10, 0, 24, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            DateTimeVisit = new DateTime(2021, 4, 11, 12, 10, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            DateTimeVisit = new DateTime(2021, 6, 25, 12, 21, 6, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 16,
                            DateTimeVisit = new DateTime(2017, 7, 18, 16, 18, 40, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            DateTimeVisit = new DateTime(2021, 4, 15, 12, 3, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            DateTimeVisit = new DateTime(2021, 2, 2, 14, 35, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            DateTimeVisit = new DateTime(2019, 8, 19, 19, 42, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 20,
                            DateTimeVisit = new DateTime(2019, 1, 29, 22, 11, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 21,
                            DateTimeVisit = new DateTime(2020, 3, 28, 15, 14, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 22,
                            DateTimeVisit = new DateTime(2018, 12, 21, 0, 17, 37, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 23,
                            DateTimeVisit = new DateTime(2018, 6, 7, 14, 31, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 24,
                            DateTimeVisit = new DateTime(2020, 3, 11, 14, 52, 18, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 25,
                            DateTimeVisit = new DateTime(2020, 7, 1, 8, 47, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 26,
                            DateTimeVisit = new DateTime(2021, 1, 22, 20, 27, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 27,
                            DateTimeVisit = new DateTime(2018, 10, 6, 14, 57, 45, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 28,
                            DateTimeVisit = new DateTime(2018, 5, 1, 2, 0, 38, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 29,
                            DateTimeVisit = new DateTime(2017, 2, 14, 17, 16, 9, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 30,
                            DateTimeVisit = new DateTime(2020, 9, 18, 5, 8, 52, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 31,
                            DateTimeVisit = new DateTime(2021, 10, 25, 16, 20, 8, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 32,
                            DateTimeVisit = new DateTime(2019, 10, 5, 2, 32, 3, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 33,
                            DateTimeVisit = new DateTime(2018, 4, 27, 23, 35, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 34,
                            DateTimeVisit = new DateTime(2018, 9, 5, 21, 58, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            DateTimeVisit = new DateTime(2020, 9, 27, 18, 35, 13, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            DateTimeVisit = new DateTime(2020, 3, 25, 3, 35, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            DateTimeVisit = new DateTime(2019, 8, 30, 21, 7, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            DateTimeVisit = new DateTime(2017, 9, 28, 11, 51, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            DateTimeVisit = new DateTime(2019, 2, 4, 21, 29, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            DateTimeVisit = new DateTime(2018, 5, 26, 17, 56, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            DateTimeVisit = new DateTime(2021, 4, 3, 5, 22, 47, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            DateTimeVisit = new DateTime(2018, 12, 19, 11, 12, 41, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            DateTimeVisit = new DateTime(2020, 11, 21, 18, 48, 20, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            DateTimeVisit = new DateTime(2021, 2, 17, 5, 8, 47, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            DateTimeVisit = new DateTime(2020, 5, 3, 6, 27, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            DateTimeVisit = new DateTime(2017, 6, 14, 17, 10, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 47,
                            DateTimeVisit = new DateTime(2019, 5, 17, 21, 3, 37, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 48,
                            DateTimeVisit = new DateTime(2021, 3, 20, 1, 55, 54, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 49,
                            DateTimeVisit = new DateTime(2020, 7, 11, 9, 27, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 50,
                            DateTimeVisit = new DateTime(2019, 1, 14, 11, 40, 13, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 51,
                            DateTimeVisit = new DateTime(2017, 2, 26, 8, 57, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 52,
                            DateTimeVisit = new DateTime(2017, 1, 10, 15, 18, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 53,
                            DateTimeVisit = new DateTime(2019, 4, 30, 15, 41, 8, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 54,
                            DateTimeVisit = new DateTime(2018, 8, 20, 13, 28, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 55,
                            DateTimeVisit = new DateTime(2020, 7, 25, 19, 6, 35, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 56,
                            DateTimeVisit = new DateTime(2020, 4, 20, 11, 24, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 57,
                            DateTimeVisit = new DateTime(2018, 11, 12, 22, 3, 24, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 58,
                            DateTimeVisit = new DateTime(2018, 3, 31, 2, 31, 58, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 59,
                            DateTimeVisit = new DateTime(2019, 9, 12, 5, 28, 50, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 60,
                            DateTimeVisit = new DateTime(2019, 3, 5, 4, 47, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 61,
                            DateTimeVisit = new DateTime(2019, 2, 11, 21, 39, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 62,
                            DateTimeVisit = new DateTime(2019, 11, 6, 14, 12, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 63,
                            DateTimeVisit = new DateTime(2019, 7, 23, 13, 51, 24, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 64,
                            DateTimeVisit = new DateTime(2019, 7, 4, 22, 27, 23, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 65,
                            DateTimeVisit = new DateTime(2020, 6, 4, 2, 56, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 66,
                            DateTimeVisit = new DateTime(2017, 4, 25, 1, 9, 51, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 67,
                            DateTimeVisit = new DateTime(2020, 4, 30, 19, 39, 35, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 68,
                            DateTimeVisit = new DateTime(2020, 9, 28, 17, 39, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 69,
                            DateTimeVisit = new DateTime(2020, 5, 7, 7, 46, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 70,
                            DateTimeVisit = new DateTime(2021, 1, 25, 22, 57, 53, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 71,
                            DateTimeVisit = new DateTime(2017, 9, 12, 7, 23, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 72,
                            DateTimeVisit = new DateTime(2019, 5, 11, 14, 24, 33, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 73,
                            DateTimeVisit = new DateTime(2017, 10, 22, 5, 18, 6, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 74,
                            DateTimeVisit = new DateTime(2021, 2, 16, 16, 58, 9, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 75,
                            DateTimeVisit = new DateTime(2018, 7, 19, 5, 1, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 76,
                            DateTimeVisit = new DateTime(2017, 2, 2, 17, 13, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 77,
                            DateTimeVisit = new DateTime(2018, 11, 23, 19, 40, 51, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 78,
                            DateTimeVisit = new DateTime(2018, 3, 12, 22, 35, 28, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 79,
                            DateTimeVisit = new DateTime(2021, 8, 1, 20, 37, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 80,
                            DateTimeVisit = new DateTime(2017, 11, 10, 3, 49, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 81,
                            DateTimeVisit = new DateTime(2018, 6, 28, 12, 36, 38, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 82,
                            DateTimeVisit = new DateTime(2017, 5, 10, 2, 14, 24, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 83,
                            DateTimeVisit = new DateTime(2018, 9, 14, 6, 45, 50, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 84,
                            DateTimeVisit = new DateTime(2018, 11, 25, 19, 48, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 85,
                            DateTimeVisit = new DateTime(2018, 5, 15, 10, 24, 37, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 86,
                            DateTimeVisit = new DateTime(2020, 7, 9, 14, 14, 12, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 87,
                            DateTimeVisit = new DateTime(2020, 4, 28, 0, 3, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 88,
                            DateTimeVisit = new DateTime(2020, 7, 1, 23, 18, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 89,
                            DateTimeVisit = new DateTime(2018, 1, 4, 14, 3, 28, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 90,
                            DateTimeVisit = new DateTime(2020, 3, 1, 19, 23, 36, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 91,
                            DateTimeVisit = new DateTime(2018, 3, 7, 18, 44, 55, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 92,
                            DateTimeVisit = new DateTime(2021, 3, 23, 9, 48, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 93,
                            DateTimeVisit = new DateTime(2018, 11, 10, 19, 36, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 94,
                            DateTimeVisit = new DateTime(2020, 9, 23, 6, 54, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 95,
                            DateTimeVisit = new DateTime(2019, 2, 6, 9, 28, 23, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 96,
                            DateTimeVisit = new DateTime(2017, 4, 21, 4, 22, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 97,
                            DateTimeVisit = new DateTime(2019, 3, 20, 10, 32, 51, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 98,
                            DateTimeVisit = new DateTime(2021, 3, 11, 9, 33, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 99,
                            DateTimeVisit = new DateTime(2021, 6, 8, 16, 23, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 100,
                            DateTimeVisit = new DateTime(2018, 12, 1, 18, 29, 12, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 101,
                            DateTimeVisit = new DateTime(2017, 12, 8, 11, 43, 8, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 102,
                            DateTimeVisit = new DateTime(2019, 7, 13, 17, 36, 6, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 103,
                            DateTimeVisit = new DateTime(2021, 8, 6, 6, 20, 40, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 104,
                            DateTimeVisit = new DateTime(2019, 4, 11, 1, 41, 2, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 105,
                            DateTimeVisit = new DateTime(2017, 2, 23, 17, 29, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 106,
                            DateTimeVisit = new DateTime(2018, 8, 11, 7, 45, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 107,
                            DateTimeVisit = new DateTime(2020, 1, 12, 22, 12, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 12
                        },
                        new
                        {
                            Id = 108,
                            DateTimeVisit = new DateTime(2018, 1, 6, 12, 54, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 12
                        },
                        new
                        {
                            Id = 109,
                            DateTimeVisit = new DateTime(2020, 12, 26, 21, 39, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 110,
                            DateTimeVisit = new DateTime(2017, 3, 16, 15, 5, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 111,
                            DateTimeVisit = new DateTime(2017, 4, 20, 5, 55, 52, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 112,
                            DateTimeVisit = new DateTime(2020, 7, 24, 13, 40, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 113,
                            DateTimeVisit = new DateTime(2018, 6, 22, 18, 6, 11, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 114,
                            DateTimeVisit = new DateTime(2017, 8, 26, 15, 51, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 115,
                            DateTimeVisit = new DateTime(2021, 8, 31, 5, 23, 34, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 116,
                            DateTimeVisit = new DateTime(2018, 7, 26, 8, 37, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 117,
                            DateTimeVisit = new DateTime(2021, 1, 16, 21, 39, 22, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 118,
                            DateTimeVisit = new DateTime(2021, 7, 22, 8, 16, 28, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 119,
                            DateTimeVisit = new DateTime(2021, 1, 14, 1, 15, 19, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 120,
                            DateTimeVisit = new DateTime(2020, 9, 20, 1, 54, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 121,
                            DateTimeVisit = new DateTime(2018, 10, 21, 14, 19, 55, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 122,
                            DateTimeVisit = new DateTime(2021, 7, 23, 10, 33, 11, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 123,
                            DateTimeVisit = new DateTime(2017, 6, 17, 15, 48, 9, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 124,
                            DateTimeVisit = new DateTime(2020, 12, 31, 1, 35, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 125,
                            DateTimeVisit = new DateTime(2018, 9, 11, 17, 25, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 126,
                            DateTimeVisit = new DateTime(2021, 5, 14, 12, 47, 20, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 127,
                            DateTimeVisit = new DateTime(2021, 5, 25, 8, 0, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 128,
                            DateTimeVisit = new DateTime(2017, 12, 22, 12, 36, 13, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 129,
                            DateTimeVisit = new DateTime(2018, 10, 5, 20, 42, 19, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 130,
                            DateTimeVisit = new DateTime(2021, 1, 21, 14, 51, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 131,
                            DateTimeVisit = new DateTime(2019, 9, 7, 20, 53, 50, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 132,
                            DateTimeVisit = new DateTime(2018, 7, 6, 23, 19, 54, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 133,
                            DateTimeVisit = new DateTime(2018, 7, 28, 19, 23, 51, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 134,
                            DateTimeVisit = new DateTime(2018, 6, 24, 15, 20, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 135,
                            DateTimeVisit = new DateTime(2020, 9, 26, 5, 18, 32, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 136,
                            DateTimeVisit = new DateTime(2019, 10, 10, 8, 12, 5, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 137,
                            DateTimeVisit = new DateTime(2021, 7, 28, 8, 6, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 138,
                            DateTimeVisit = new DateTime(2020, 3, 28, 18, 15, 22, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 139,
                            DateTimeVisit = new DateTime(2017, 7, 24, 15, 30, 33, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 140,
                            DateTimeVisit = new DateTime(2020, 8, 28, 16, 51, 22, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 141,
                            DateTimeVisit = new DateTime(2020, 5, 21, 5, 14, 49, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 142,
                            DateTimeVisit = new DateTime(2017, 2, 15, 1, 20, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 143,
                            DateTimeVisit = new DateTime(2020, 6, 30, 14, 51, 19, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 144,
                            DateTimeVisit = new DateTime(2021, 8, 13, 13, 10, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 145,
                            DateTimeVisit = new DateTime(2018, 10, 4, 3, 40, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 146,
                            DateTimeVisit = new DateTime(2018, 6, 6, 18, 16, 59, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 147,
                            DateTimeVisit = new DateTime(2019, 7, 24, 3, 54, 53, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 148,
                            DateTimeVisit = new DateTime(2021, 1, 9, 16, 57, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 149,
                            DateTimeVisit = new DateTime(2019, 11, 17, 15, 42, 25, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 150,
                            DateTimeVisit = new DateTime(2021, 5, 5, 14, 3, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 151,
                            DateTimeVisit = new DateTime(2017, 2, 27, 20, 54, 53, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 152,
                            DateTimeVisit = new DateTime(2017, 7, 22, 15, 29, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 153,
                            DateTimeVisit = new DateTime(2020, 12, 21, 21, 30, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 154,
                            DateTimeVisit = new DateTime(2020, 7, 12, 4, 41, 11, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 155,
                            DateTimeVisit = new DateTime(2020, 12, 4, 17, 22, 49, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 156,
                            DateTimeVisit = new DateTime(2017, 4, 8, 14, 22, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 157,
                            DateTimeVisit = new DateTime(2017, 11, 18, 15, 0, 31, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 158,
                            DateTimeVisit = new DateTime(2021, 7, 31, 19, 58, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 159,
                            DateTimeVisit = new DateTime(2021, 5, 24, 21, 28, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 160,
                            DateTimeVisit = new DateTime(2020, 7, 5, 18, 55, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 161,
                            DateTimeVisit = new DateTime(2017, 1, 11, 12, 56, 25, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 162,
                            DateTimeVisit = new DateTime(2018, 11, 14, 23, 48, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 163,
                            DateTimeVisit = new DateTime(2020, 1, 26, 5, 24, 45, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 164,
                            DateTimeVisit = new DateTime(2020, 9, 28, 20, 0, 22, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 165,
                            DateTimeVisit = new DateTime(2019, 5, 2, 7, 24, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("KellyTestProject.Model.Visit", b =>
                {
                    b.HasOne("KellyTestProject.Model.Section", "Section")
                        .WithMany("Visits")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KellyTestProject.Model.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KellyTestProject.Model.Section", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("KellyTestProject.Model.User", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
