// <auto-generated />
using System;
using KellyTestProject.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KellyTestProject.Migrations
{
    [DbContext(typeof(MsSqlContext))]
    partial class MsSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KellyTestProject.Model.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Раздел 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Раздел 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Раздел 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Раздел 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Раздел 5"
                        });
                });

            modelBuilder.Entity("KellyTestProject.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Иван",
                            Patronymic = "Иванович",
                            Surname = "Иванов"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Пётр",
                            Patronymic = "Петрович",
                            Surname = "Петров"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Семён",
                            Patronymic = "Семёныч",
                            Surname = "Смирнов"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Александр",
                            Patronymic = "Александрович",
                            Surname = "Александров"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Максим",
                            Patronymic = "Максимы",
                            Surname = "Максимов"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Имя1",
                            Patronymic = "Отчество1",
                            Surname = "Фамилия1"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Имя2",
                            Patronymic = "Отчество2",
                            Surname = "Фамилия2"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Имя3",
                            Patronymic = "Отчество3",
                            Surname = "Фамилия3"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Имя4",
                            Patronymic = "Отчество4",
                            Surname = "Фамилия4"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Имя5",
                            Patronymic = "Отчество5",
                            Surname = "Фамилия5"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Имя6",
                            Patronymic = "Отчество6",
                            Surname = "Фамилия6"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Имя7",
                            Patronymic = "Отчество7",
                            Surname = "Фамилия7"
                        });
                });

            modelBuilder.Entity("KellyTestProject.Model.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTimeVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("UserId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTimeVisit = new DateTime(2019, 9, 11, 20, 28, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTimeVisit = new DateTime(2019, 8, 21, 15, 19, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateTimeVisit = new DateTime(2019, 7, 17, 1, 9, 50, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            DateTimeVisit = new DateTime(2017, 7, 8, 12, 16, 20, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            DateTimeVisit = new DateTime(2019, 12, 28, 9, 38, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateTimeVisit = new DateTime(2020, 2, 27, 8, 13, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            DateTimeVisit = new DateTime(2021, 5, 26, 18, 58, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            DateTimeVisit = new DateTime(2018, 1, 1, 17, 24, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            DateTimeVisit = new DateTime(2020, 2, 21, 21, 33, 43, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            DateTimeVisit = new DateTime(2021, 4, 28, 17, 18, 54, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            DateTimeVisit = new DateTime(2020, 6, 5, 5, 23, 14, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            DateTimeVisit = new DateTime(2017, 12, 30, 1, 12, 35, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            DateTimeVisit = new DateTime(2021, 9, 10, 14, 10, 54, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            DateTimeVisit = new DateTime(2018, 4, 21, 14, 7, 28, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            DateTimeVisit = new DateTime(2018, 12, 30, 19, 19, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            DateTimeVisit = new DateTime(2017, 4, 16, 10, 16, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            DateTimeVisit = new DateTime(2019, 3, 14, 17, 6, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            DateTimeVisit = new DateTime(2017, 7, 5, 23, 13, 38, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            DateTimeVisit = new DateTime(2020, 6, 21, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            DateTimeVisit = new DateTime(2019, 12, 24, 3, 19, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 21,
                            DateTimeVisit = new DateTime(2020, 6, 28, 20, 46, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 22,
                            DateTimeVisit = new DateTime(2017, 6, 23, 15, 30, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 23,
                            DateTimeVisit = new DateTime(2020, 12, 1, 16, 8, 11, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 24,
                            DateTimeVisit = new DateTime(2021, 6, 21, 11, 52, 33, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 25,
                            DateTimeVisit = new DateTime(2019, 4, 9, 18, 8, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 26,
                            DateTimeVisit = new DateTime(2020, 12, 21, 11, 28, 11, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 27,
                            DateTimeVisit = new DateTime(2020, 9, 9, 8, 49, 2, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 28,
                            DateTimeVisit = new DateTime(2017, 8, 4, 10, 3, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 29,
                            DateTimeVisit = new DateTime(2020, 3, 7, 13, 24, 37, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 30,
                            DateTimeVisit = new DateTime(2020, 4, 12, 22, 15, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 31,
                            DateTimeVisit = new DateTime(2019, 1, 23, 22, 24, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 1,
                            UserId = 12
                        },
                        new
                        {
                            Id = 32,
                            DateTimeVisit = new DateTime(2021, 12, 1, 10, 41, 49, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            DateTimeVisit = new DateTime(2017, 1, 18, 5, 7, 58, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            DateTimeVisit = new DateTime(2018, 8, 14, 10, 7, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            DateTimeVisit = new DateTime(2017, 3, 31, 5, 1, 18, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 36,
                            DateTimeVisit = new DateTime(2018, 7, 25, 5, 38, 40, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 37,
                            DateTimeVisit = new DateTime(2019, 3, 3, 21, 52, 53, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 38,
                            DateTimeVisit = new DateTime(2017, 3, 19, 13, 20, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 39,
                            DateTimeVisit = new DateTime(2018, 9, 19, 6, 37, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 40,
                            DateTimeVisit = new DateTime(2021, 1, 6, 17, 53, 32, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 41,
                            DateTimeVisit = new DateTime(2021, 8, 23, 5, 35, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 42,
                            DateTimeVisit = new DateTime(2018, 9, 28, 2, 7, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 43,
                            DateTimeVisit = new DateTime(2018, 10, 1, 7, 0, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 44,
                            DateTimeVisit = new DateTime(2020, 5, 8, 16, 36, 59, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 45,
                            DateTimeVisit = new DateTime(2020, 9, 29, 0, 38, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 46,
                            DateTimeVisit = new DateTime(2019, 2, 22, 17, 38, 25, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 47,
                            DateTimeVisit = new DateTime(2019, 7, 24, 16, 10, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 48,
                            DateTimeVisit = new DateTime(2017, 4, 11, 22, 52, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 49,
                            DateTimeVisit = new DateTime(2020, 3, 4, 9, 5, 57, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 50,
                            DateTimeVisit = new DateTime(2018, 2, 19, 9, 54, 2, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 51,
                            DateTimeVisit = new DateTime(2017, 12, 19, 23, 22, 55, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 52,
                            DateTimeVisit = new DateTime(2018, 12, 10, 20, 7, 12, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 53,
                            DateTimeVisit = new DateTime(2017, 7, 19, 5, 40, 54, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 54,
                            DateTimeVisit = new DateTime(2020, 4, 2, 0, 31, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 2,
                            UserId = 12
                        },
                        new
                        {
                            Id = 55,
                            DateTimeVisit = new DateTime(2018, 5, 2, 18, 31, 37, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            DateTimeVisit = new DateTime(2017, 2, 11, 18, 10, 4, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 57,
                            DateTimeVisit = new DateTime(2020, 7, 14, 11, 23, 52, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            DateTimeVisit = new DateTime(2019, 11, 19, 3, 29, 50, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            DateTimeVisit = new DateTime(2018, 1, 23, 8, 20, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 60,
                            DateTimeVisit = new DateTime(2019, 10, 1, 10, 22, 10, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 61,
                            DateTimeVisit = new DateTime(2020, 4, 12, 12, 36, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 62,
                            DateTimeVisit = new DateTime(2019, 8, 15, 21, 7, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 63,
                            DateTimeVisit = new DateTime(2019, 9, 18, 16, 11, 24, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 64,
                            DateTimeVisit = new DateTime(2020, 8, 3, 11, 29, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 65,
                            DateTimeVisit = new DateTime(2017, 1, 30, 8, 5, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 66,
                            DateTimeVisit = new DateTime(2019, 4, 28, 8, 54, 58, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 67,
                            DateTimeVisit = new DateTime(2021, 9, 5, 10, 18, 11, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 68,
                            DateTimeVisit = new DateTime(2018, 11, 20, 17, 15, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 69,
                            DateTimeVisit = new DateTime(2021, 12, 15, 22, 18, 43, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 70,
                            DateTimeVisit = new DateTime(2021, 3, 29, 3, 53, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 71,
                            DateTimeVisit = new DateTime(2018, 11, 7, 1, 37, 42, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 72,
                            DateTimeVisit = new DateTime(2017, 10, 19, 17, 58, 49, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 73,
                            DateTimeVisit = new DateTime(2019, 8, 10, 6, 48, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 74,
                            DateTimeVisit = new DateTime(2019, 3, 10, 9, 24, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 75,
                            DateTimeVisit = new DateTime(2018, 3, 26, 11, 56, 37, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 76,
                            DateTimeVisit = new DateTime(2017, 7, 25, 7, 51, 25, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 77,
                            DateTimeVisit = new DateTime(2020, 6, 15, 21, 42, 51, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 78,
                            DateTimeVisit = new DateTime(2020, 5, 17, 13, 44, 45, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 79,
                            DateTimeVisit = new DateTime(2021, 8, 17, 23, 26, 2, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 80,
                            DateTimeVisit = new DateTime(2020, 12, 9, 13, 42, 16, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 81,
                            DateTimeVisit = new DateTime(2021, 3, 21, 9, 29, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 82,
                            DateTimeVisit = new DateTime(2018, 3, 22, 23, 9, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 83,
                            DateTimeVisit = new DateTime(2017, 3, 24, 14, 10, 19, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 84,
                            DateTimeVisit = new DateTime(2017, 11, 10, 17, 42, 8, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 85,
                            DateTimeVisit = new DateTime(2018, 2, 16, 12, 5, 24, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 86,
                            DateTimeVisit = new DateTime(2021, 11, 6, 14, 29, 6, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 87,
                            DateTimeVisit = new DateTime(2020, 3, 6, 18, 12, 28, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 88,
                            DateTimeVisit = new DateTime(2017, 7, 10, 18, 47, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 3,
                            UserId = 12
                        },
                        new
                        {
                            Id = 89,
                            DateTimeVisit = new DateTime(2020, 2, 5, 5, 48, 35, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 90,
                            DateTimeVisit = new DateTime(2020, 11, 11, 1, 3, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 91,
                            DateTimeVisit = new DateTime(2018, 11, 5, 7, 27, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 92,
                            DateTimeVisit = new DateTime(2021, 2, 7, 7, 35, 36, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 93,
                            DateTimeVisit = new DateTime(2019, 12, 21, 18, 12, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 94,
                            DateTimeVisit = new DateTime(2019, 9, 12, 9, 27, 7, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 95,
                            DateTimeVisit = new DateTime(2021, 8, 18, 18, 28, 47, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 96,
                            DateTimeVisit = new DateTime(2018, 10, 1, 21, 40, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 97,
                            DateTimeVisit = new DateTime(2019, 11, 4, 23, 7, 13, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 98,
                            DateTimeVisit = new DateTime(2017, 12, 22, 8, 42, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 99,
                            DateTimeVisit = new DateTime(2018, 3, 2, 20, 43, 50, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 100,
                            DateTimeVisit = new DateTime(2021, 3, 25, 5, 56, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 101,
                            DateTimeVisit = new DateTime(2019, 4, 12, 21, 32, 47, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 102,
                            DateTimeVisit = new DateTime(2021, 7, 27, 12, 7, 2, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 103,
                            DateTimeVisit = new DateTime(2021, 3, 20, 14, 46, 29, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 104,
                            DateTimeVisit = new DateTime(2020, 11, 29, 19, 24, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 105,
                            DateTimeVisit = new DateTime(2020, 1, 7, 21, 30, 53, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 106,
                            DateTimeVisit = new DateTime(2020, 12, 24, 19, 36, 40, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 107,
                            DateTimeVisit = new DateTime(2020, 2, 23, 3, 31, 18, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 108,
                            DateTimeVisit = new DateTime(2018, 2, 2, 9, 28, 26, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 109,
                            DateTimeVisit = new DateTime(2017, 11, 30, 2, 47, 0, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 110,
                            DateTimeVisit = new DateTime(2021, 8, 1, 0, 52, 45, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 111,
                            DateTimeVisit = new DateTime(2017, 6, 20, 9, 40, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 112,
                            DateTimeVisit = new DateTime(2020, 12, 21, 11, 51, 41, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 113,
                            DateTimeVisit = new DateTime(2018, 1, 27, 16, 15, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 114,
                            DateTimeVisit = new DateTime(2018, 12, 7, 7, 50, 3, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 115,
                            DateTimeVisit = new DateTime(2019, 5, 4, 15, 5, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 4,
                            UserId = 12
                        },
                        new
                        {
                            Id = 116,
                            DateTimeVisit = new DateTime(2018, 11, 14, 2, 39, 54, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 117,
                            DateTimeVisit = new DateTime(2017, 3, 15, 20, 9, 44, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 118,
                            DateTimeVisit = new DateTime(2018, 8, 1, 12, 42, 49, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 119,
                            DateTimeVisit = new DateTime(2017, 4, 9, 12, 36, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 120,
                            DateTimeVisit = new DateTime(2017, 12, 18, 7, 48, 9, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 121,
                            DateTimeVisit = new DateTime(2019, 11, 16, 3, 53, 3, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 122,
                            DateTimeVisit = new DateTime(2019, 12, 20, 5, 42, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 123,
                            DateTimeVisit = new DateTime(2018, 8, 9, 1, 39, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 124,
                            DateTimeVisit = new DateTime(2021, 11, 27, 10, 28, 30, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 125,
                            DateTimeVisit = new DateTime(2018, 2, 16, 9, 37, 12, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 126,
                            DateTimeVisit = new DateTime(2017, 8, 24, 7, 14, 39, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 127,
                            DateTimeVisit = new DateTime(2018, 9, 22, 11, 58, 34, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 128,
                            DateTimeVisit = new DateTime(2020, 10, 21, 10, 33, 53, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 129,
                            DateTimeVisit = new DateTime(2018, 5, 16, 5, 8, 47, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 130,
                            DateTimeVisit = new DateTime(2020, 3, 18, 2, 28, 40, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 131,
                            DateTimeVisit = new DateTime(2018, 7, 14, 21, 55, 46, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 132,
                            DateTimeVisit = new DateTime(2018, 4, 18, 2, 12, 55, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 133,
                            DateTimeVisit = new DateTime(2017, 12, 9, 6, 13, 27, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 134,
                            DateTimeVisit = new DateTime(2020, 3, 16, 7, 41, 56, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 135,
                            DateTimeVisit = new DateTime(2017, 7, 21, 6, 22, 2, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 136,
                            DateTimeVisit = new DateTime(2020, 7, 19, 10, 34, 57, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 137,
                            DateTimeVisit = new DateTime(2021, 10, 26, 22, 35, 1, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 138,
                            DateTimeVisit = new DateTime(2018, 2, 17, 7, 57, 22, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 139,
                            DateTimeVisit = new DateTime(2021, 8, 28, 9, 24, 47, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 140,
                            DateTimeVisit = new DateTime(2019, 1, 18, 5, 41, 17, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 141,
                            DateTimeVisit = new DateTime(2021, 7, 5, 0, 10, 21, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 142,
                            DateTimeVisit = new DateTime(2017, 11, 27, 22, 56, 35, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 143,
                            DateTimeVisit = new DateTime(2020, 7, 3, 5, 12, 59, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 144,
                            DateTimeVisit = new DateTime(2019, 4, 28, 18, 7, 24, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 145,
                            DateTimeVisit = new DateTime(2018, 3, 15, 4, 34, 33, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 146,
                            DateTimeVisit = new DateTime(2018, 10, 8, 9, 48, 13, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 147,
                            DateTimeVisit = new DateTime(2018, 11, 5, 4, 32, 48, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 148,
                            DateTimeVisit = new DateTime(2017, 10, 7, 0, 34, 18, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 12
                        },
                        new
                        {
                            Id = 149,
                            DateTimeVisit = new DateTime(2021, 2, 2, 7, 34, 23, 0, DateTimeKind.Unspecified),
                            SectionId = 5,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("KellyTestProject.Model.Visit", b =>
                {
                    b.HasOne("KellyTestProject.Model.Section", "Section")
                        .WithMany("Visits")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KellyTestProject.Model.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KellyTestProject.Model.Section", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("KellyTestProject.Model.User", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
